media:
  input: static/images
  output: /images

content:
  - name: english_lectures
    label: English Lectures
    type: collection
    path: content/en/posts
    format: md
    fields:
      - { name: title, label: Title, type: string }
      - { name: body, label: Lecture Content, type: rich-text }

  - name: arabic_lectures
    label: محاضرات عربية
    type: collection
    path: content/ar/posts
    format: md
    fields:
      - { name: title, label: العنوان, type: string }
      - { name: body, label: محتوى المحاضرة, type: rich-text }
