baseURL = "https://zahi.netlify.app/"
title = "زاهي"
languageCode = "ar"
defaultContentLanguage = "ar"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
series = "series"

# Use Hugo Modules to import theme from parent directory
[module]
  [[module.imports]]
    path = "github.com/mohamedelhefni/zahi"
    
  [[module.mounts]]
    source = "content"
    target = "content"
    
  [[module.mounts]]
    source = "static"
    target = "static"

[menu]
[[menu.main]]
identifier = "الرئيسية"
name = "الرئيسية"
url = "/"
weight = 10

[[menu.main]]
identifier = "المقالات"
name = "المدونه"
url = "/posts"
weight = 20

[[menu.main]]
identifier = "السلاسل"
name = "السلاسل"
url = "/series"
weight = 25

[[menu.main]]
identifier = "الخريطة"
name = "الخريطة"
url = "/graph"
weight = 30

[params]
github = "https://www.github.com/mohamedelhefni"
mail = "mailto:mohamed.elhefni@outlook.com"
site = "https://hefni101.netlify.app/"

# [services]
# [services.disqus]
# shortname = 'foobar'
