baseURL = "https://mynewhugosite.com"
title = "زاهي"
theme = "zahi"
languageCode = "ar"
defaultContentLanguage = "ar"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
series = "series"

[menu]
[[menu.main]]
identifier = "الرئيسية"
name = "الرئيسية"
url = "/"
weight = 10


[[menu.main]]
identifier = "المقالات"
name = "المدونه"
url = "/posts"
weight = 20

[[menu.main]]
identifier = "السلاسل"
name = "السلاسل"
url = "/series"
weight = 25

[[menu.main]]
identifier = "الخريطة"
name = "الخريطة"
url = "/graph"
weight = 30


[params]
github = "https://www.github.com/mohamedelhefni"
mail = "mailto:mohamed.elhefni@outlook.com"
site = "https://hefni101.netlify.app/"

# [services]
# [services.disqus]
# shortname = 'foobar'
